feat: loadUserByUsername부분 POST /getUser 호출하게 변경 & authenticate api 구현
f-lab-edu/momukji-services pull request #66
Opened 2022-07-18 12:51 UTC by sue4869

1. loadUserByUsername부분 POST /getUser 호출하게 변경
  -- feign이 유레카서버를 이용하여 [auth]가  [user]의 POST/getUser 호출하도록 구현
  -- [user]의 POST/getUser 호출하는 것에 대한 테스트 api : Get/callUser
  -- [auth]가  [user]의 POST/getUser 호출하는 테스트 완료
![image](https://user-images.githubusercontent.com/68679529/179513895-4d9abb73-7c08-4d84-8f50-a071f639b511.png)
 -- loadUserByUsername가 UserServiceClient를 통해  [user]의 POST/getUser 호출하도록 함. 

2. authenticate api 구현 => 토큰 생성 api
 -- authenticate api가 loadUserByUsername 사용함. 
 -- authenticate api 테스트 완료. 
![image](https://user-images.githubusercontent.com/68679529/179514952-d63f92ec-102a-4555-bfd1-d255a75c677f.png)

2022-07-18 13:17 UTC, deepredk requested changes
고생하셨습니다 ㅎㅎ

2022-07-18 13:17 UTC, deepredk commented on auth/build.gradle
> +	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign' //feign
이름에도 이미 feign이라 돼있어서 요런건 주석 안달아도 될거같슴다

2022-07-18 13:17 UTC, deepredk commented on auth/src/main/java/kr/flab/momukji/auth/controller/AuthController.java
> +
불필요한 줄바꿈이요!

2022-07-18 13:17 UTC, deepredk commented on auth/src/main/java/kr/flab/momukji/auth/controller/AuthController.java
> +    public ResponseEntity<TokenDto> authorize(@Valid @RequestBody LoginDto loginDto) {
컨트롤러보다는 서비스에 적합한 코드들이 많은 것 같습니다
서비스로 한번 감싸주는게 좋을거같아요!

2022-07-18 13:17 UTC, deepredk commented on auth/src/main/java/kr/flab/momukji/auth/dto/request/GetUserDto.java
> +    public GetUserDto() { }
요 기본생성자 없어도 서버 잘 실행되는거같은데
어떤거 때문에 기본생성자 넣어주신거에요??

2022-07-18 13:17 UTC, deepredk commented on auth/src/main/java/kr/flab/momukji/auth/dto/request/GetUserDto.java
> +    public GetUserDto(String email, String authCode) {
Lombok AllArgs 어노테이션 쓰면 좋을거같아요!

2022-07-18 13:17 UTC, deepredk commented on auth/src/main/java/kr/flab/momukji/auth/service/CustomUserDetailsService.java
> +
불필요한 줄바꿈이요!

2022-07-18 13:17 UTC, deepredk commented on auth/src/main/java/kr/flab/momukji/auth/dto/request/CallUserDto.java
> +    private String resultCode;
Enum ResultCode으로는 매칭 안되나요??

2022-07-18 13:17 UTC, deepredk commented on auth/src/main/java/kr/flab/momukji/auth/service/CustomUserDetailsService.java
> +        return new org.springframework.security.core.userdetails.User(user.getEmail(),user.getPassword(),grantedAuthorities);
컴마 뒤 띄어쓰기요!
checkstyle 활성화 되어있으신거죠??

2022-07-18 14:02 UTC, sue4869 commented on auth/src/main/java/kr/flab/momukji/auth/dto/request/GetUserDto.java
> +    public GetUserDto() { }
에러가 났었었어요. 에러에서 기본 생성자를 넣어주라는 말에 의해 넣어주었습니다.

2022-07-18 14:03 UTC, sue4869 commented on auth/build.gradle
> +	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign' //feign
넵

2022-07-18 14:23 UTC, sue4869 commented on auth/src/main/java/kr/flab/momukji/auth/dto/request/CallUserDto.java
> +    private String resultCode;
넵 안되어요

2022-07-18 14:25 UTC, sue4869 commented on auth/src/main/java/kr/flab/momukji/auth/dto/request/GetUserDto.java
> +    public GetUserDto(String email, String authCode) {
@NoArgsConstructor와 @AllArgsConstructor 사용하겠습니다

2022-07-18 14:25 UTC, sue4869 commented on auth/src/main/java/kr/flab/momukji/auth/dto/request/GetUserDto.java
> +    public GetUserDto() { }
@NoArgsConstructor사용해서 해당 코드 지워주겠습니다.

2022-07-18 14:38 UTC, sue4869 commented on auth/src/main/java/kr/flab/momukji/auth/controller/AuthController.java
> +    public ResponseEntity<TokenDto> authorize(@Valid @RequestBody LoginDto loginDto) {
서비스로 감싸준 버전 테스트 완료
![Uploading image.png…]()

2022-07-19 01:45 UTC, sue4869 commented on auth/src/main/java/kr/flab/momukji/auth/service/CustomUserDetailsService.java
> +        return new org.springframework.security.core.userdetails.User(user.getEmail(),user.getPassword(),grantedAuthorities);
띄어쓰기 반영했습니다

2022-07-20 05:30 UTC, deepredk approved these changes

2022-07-20 05:41 UTC, sue4869 commented on auth/src/main/java/kr/flab/momukji/auth/service/CustomUserDetailsService.java
> +        return new org.springframework.security.core.userdetails.User(user.getEmail(), user.getPassword(),grantedAuthorities);
옹 고쳤는데 왜 반영이 안되었데여

2022-07-20 05:48 UTC, sue4869 commented on auth/src/main/java/kr/flab/momukji/auth/service/CustomUserDetailsService.java
> +        return new org.springframework.security.core.userdetails.User(user.getEmail(), user.getPassword(),grantedAuthorities);
띄어쓰기 수정 전 이전 버전 같습니당 반영했어용!

2022-07-20 06:01 UTC, merged